# serverless.yml

service: fitbio

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  stage: ${opt:stage, self:provider.stage}
  databaseName: 'fitbio-${self:custom.stage}'
  weightTableName: 'weights'

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  environment:
    FITBIO_DB: ${self:custom.databaseName}
    WEIGHT_COLLECTION: ${self:custom.weightTableName}

functions:
  get_weight:
    handler: wsgi.handler
    events:
      - http:
          path: /weight
          method: GET
          authorizer: aws_iam
  insert_weight:
    handler: wsgi.handler
    events:
      - http:
          path: /weight
          method: POST
          authorizer: aws_iam
