# serverless.yml

service: fitbio

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  stage: ${opt:stage, self:provider.stage}
  databaseName: 'fitbio-${self:custom.stage}'
  weightTableName: 'weights'

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  environment:
    FITBIO_DB: ${self:custom.databaseName}
    WEIGHT_COLLECTION: ${self:custom.weightTableName}

Resources:
  GatewayResponseDefault4XX:
    Type: 'AWS::ApiGateway::GatewayResponse'
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseType: DEFAULT_4XX
      RestApiId:
        Ref: 'ApiGatewayRestApi'
  GatewayResponseDefault5XX:
    Type: 'AWS::ApiGateway::GatewayResponse'
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseType: DEFAULT_5XX
      RestApiId:
      Ref: 'ApiGatewayRestApi'

functions:
  get-weight:
    handler: wsgi_handler.handler
    events:
      - http:
          path: weight
          method: get
          cors: true
  #          authorizer: aws_iam
  insert-weight:
    handler: wsgi_handler.handler
    events:
      - http:
          path: weight
          method: post
          cors: true
#          authorizer: aws_iam
